import { Suspense } from "react";

import { Geist, Geist_Mono, Mulish } from "next/font/google";

import type { Metadata } from "next";

import { NavigationProgress } from "@/components/navigation-progress";
import { Providers } from "@/components/providers/index";
import { cn } from "@/lib/utils";

import "./globals.css";

const mulish = Mulish({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PERN AUTH NEW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        mulish.variable,
      )}
      suppressHydrationWarning={true}
    >
      <body className="min-h-full flex flex-col">
        <Suspense>
          <NavigationProgress />
        </Suspense>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
